### ISSUE TITLE
Flatpak import error.

### ISSUE THREAD

**Issue by ghost** [flathub/org.mattbas.Glaxnimate#5]
In the Flatpak version, it does not allow exporting to any format.
It only allows saving; I tried various formats in different folders,
but it simply throws an error, and the files remain at 0KB.
Everything else works perfectly.
I want to clarify that compiling from Git works perfectly fine; the error only occurs in Flatpak.

I would appreciate it if you could look into this issue.

**Comment by ghost** [comment]
flatpak run  org.mattbas.Glaxnimate
"2023-06-27T10:21:02" "Error" "libav" "" "Unable to find a suitable output format for '/home/eduardo/1.mp4'"
"2023-06-27T10:21:02" "Error" "libav" "" "Unable to find a suitable output format for '/home/eduardo/1.mp4'"
"2023-06-27T10:21:02" "Error" "libav" "" "Requested output format 'mpeg' is not a suitable output format"
"2023-06-27T10:21:02" "Error" "libav" "" "Requested output format 'mpeg' is not a suitable output format"

**Comment by Sunderland93** [comment]
Can confirm this issue

**Comment by mbasaglia** [comment]
is it any format or video? because it works fine for me. Maybe make sure it has the correct file type selected when exporting.

**Comment by Sunderland93** [comment]
mp4 doesn't work
